databases:
  hosts:
    mongo_db1: 
      ansible_host: {}
    mongo_db2:
      ansible_host: {}
primary:
  hosts:
    mongo_db1: 
      ansible_host: {}
secondary:
  hosts:
    mongo_db2:
      ansible_host: {}