---
- name: Install MongoDB 7.0
  hosts: mongo-database
  become: true
  vars:
    repl_set_name: "myReplSet"
    repl_set_port: 27017
    repl_set_read_preference_mode: "secondaryPreferred"
  tasks:
    - name: Modify bindIp in /etc/mongod.conf
      ansible.builtin.lineinfile:
        path: /etc/mongod.conf
        regexp: '^(bindIp: 127.0.0.1)'
        line: "bindIp: 127.0.0.1,{{ ansible_host }}"
        backrefs: true

    - name: Add replication configuration to /etc/mongod.conf
      ansible.builtin.blockinfile:
        path: /etc/mongod.conf
        block: |
          replication:
            replSetName: {{ repl_set_name }}
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        insertafter: EOF

    - name: Ensure MongoDB is started
      ansible.builtin.service:
        name: mongod
        state: started
        enabled: true

    - name: Initialize replica set on primary instance
      ansible.builtin.shell: |
        mongosh --host {{ ansible_host }}:{{ repl_set_port }} \
          --eval 'rs.initiate({_id: "{{ repl_set_name }}", members: [{_id: 0, host: "{{ ansible_host }}:{{ repl_set_port }}"}]})'
        mongosh --host {{ ansible_host }}:{{ repl_set_port }} \
          --eval 'rs.add("secondary-ip:secondary-port")'
      when: "'mongodb-primary' in inventory_hostname"
      changed_when: false

    - name: Set read preference for secondary instances
      ansible.builtin.shell: |
        mongosh --host {{ ansible_host }}:{{ repl_set_port }} --eval 'db.getMongo().setReadPref({{ repl_set_read_preference_mode }})'
      when: "'mongodb-secondary' in inventory_hostname"
      changed_when: false
