---
- name: Install MongoDB 7.0
  hosts: mongodb-database
  become: true
  vars:
    ubuntu_version: jammy
    mongodb_apt_key_url: https://pgp.mongodb.com/server-7.0.asc
    mongodb_apt_repo_url: https://repo.mongodb.org/apt/ubuntu
    mongodb_apt_key_file: /usr/share/keyrings/mongodb-server-7.0.gpg
    mongodb_repo_line: "deb [ arch=amd64,arm64 signed-by={{ mongodb_apt_key_file }} ] \
     {{ mongodb_apt_repo_url }} {{ ubuntu_version }}/mongodb-org/7.0 multiverse"
    mongodb_repo_list_file: /etc/apt/sources.list.d/mongodb-org-7.0.list
  tasks:
    - name: Install necessary packages
      ansible.builtin.apt:
        name:
          - gnupg
          - curl
        state: present

    - name: Import MongoDB public GPG key
      ansible.builtin.apt_key:
        url: "{{ mongodb_apt_key_url }}"
        keyring: "{{ mongodb_apt_key_file }}"

    - name: Create list file for MongoDB
      ansible.builtin.lineinfile:
        path: "{{ mongodb_repo_list_file }}"
        line: "{{ mongodb_repo_line }}"
        create: true
        mode: '0644'

    - name: Update APT Cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install MongoDB
      ansible.builtin.apt:
        name: mongodb-org
        state: present

    - name: Install MongoDB Shell
      ansible.builtin.apt:
        name: mongodb-mongosh
        state: present
