---
- name: Install MongoDB 7.0
  hosts: mongo-database
  become: true
  tasks:
    - name: Copy insert script to primary MongoDB server
      ansible.builtin.copy:
        src: ../scripts/insert_documents.sh
        dest: /tmp/insert_documents.sh
        mode: '0755'
      when: "'mongodb-primary' in inventory_hostname"

    - name: Copy check script to secondary MongoDB server
      ansible.builtin.copy:
        src: ../scripts/check_replication.sh
        dest: /tmp/check_replication.sh
        mode: '0755'
      when: "'mongodb-secondary' in inventory_hostname"

    - name: Execute insert script on primary MongoDB server
      ansible.builtin.command: /tmp/insert_documents.sh
      when: "'mongodb-primary' in inventory_hostname"
      changed_when: false

    - name: Execute check script on secondary MongoDB server
      ansible.builtin.command: /tmp/check_replication.sh
      register: check_replication
      when: "'mongodb-secondary' in inventory_hostname"
      changed_when: false

    - name: Display check script output
      ansible.builtin.debug:
        msg: "{{ check_replication.stdout }}"
      when: "'mongodb-secondary' in inventory_hostname"
