mongodb_apt_key_url:    https://pgp.mongodb.com/server-7.0.asc
mongodb_apt_repo_url:   https://repo.mongodb.org/apt/ubuntu
mongodb_apt_key_file:   /usr/share/keyrings/mongodb-server-7.0.gpg
mongodb_repo_line:      "deb [ arch=amd64,arm64 signed-by={{ mongodb_apt_key_file }} ] \
  {{ mongodb_apt_repo_url }} {{ ubuntu_version }}/mongodb-org/7.0 multiverse"
mongodb_repo_list_file: /etc/apt/sources.list.d/mongodb-org-7.0.list
mongodb_port: 27017
repl_set_name: myReplSet