apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  minReadySeconds: 30
  selector:
    matchLabels:
      app: backend
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: __DOCKERHUB_LOGIN__/microblog-backend:__IMAGE_TAG__
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: DB_CONNECTION_URL
          value: __CONNECTION_URL__
