name: CI

on:
  push:
    branches:
      - PIS-26-create-github-actions-pipeline
  pull_request:
    branches:
      - PIS-26-create-github-actions-pipeline

jobs:
  run-python-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: List all files
        run: ls
